### ISSUE TITLE
Showing error colorscheme not found

### ISSUE THREAD

**Issue by lakshits11** [nexxeln/nvim#1]
Hello, I am pretty much new to using lua for nvim configs, I copied your configuration and getting colorscheme not found error, also searched same colorscheme on vimawesome, not found. What to do?

![image](https://user-images.githubusercontent.com/54276661/186211228-64ab4148-f1bf-4bac-8978-fb0eb378514a.png)

EDIT: I followed the instructions on git repo of oxocarbon, but not successfull

**Comment by nexxeln** [comment]
Do you have `cargo` installed?

**Comment by lakshits11** [comment]
Yes. I also have installed rust and lua too

**Comment by nexxeln** [comment]
Whats your neovim version?

**Comment by lakshits11** [comment]
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by nexxeln** [comment]
Try running `:PackerStatus`, do you see oxocarbon there?

**Comment by ghost** [comment]
I faced that same problem.

oxocarbon's install.sh runs `cargo buid`.
so, I intslled rust with asdf and then run `cd ~/.local/share/nvim/site/pack/packer/start/oxocarbon.nvim/ && bash install.sh`.

I think that problem fixed

**Comment by lakshits11** [comment]
I used a fork of oxocarbon named `B4mbus/oxocarbon-lua.nvim` and its working good. Now I just want to ask about the language server. I want to use clangd, how to set that. Thanks!

**Comment by nexxeln** [comment]
Just do `:MasonInstall clangd` and then in [`plugin/lspconfig.lua`](https://github.com/nexxeln/nvim/blob/main/plugin/lspconfig.lua) you need to setup that language server. Here are the [docs for that](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd). That file has all the info about all the servers.

So whenever you need a new server, just install it first with mason and set it up however you want.

**Comment by nexxeln** [comment]
This fork looks great btw, I hated the way oxocarbon looked with telescope so I just removed telescope. Maybe I'll install it again and use this fork. Thanks!

**Comment by lakshits11** [comment]
I did according to docs, and now when I do LSPInfo in cpp file, I get following error. How to remove sourcekit?

![image](https://user-images.githubusercontent.com/54276661/186468495-643ee50b-de35-4b64-a2dc-981c9976d8c3.png)

**Comment by lakshits11** [comment]
Also when I open a cpp file, I get following warning:

![image](https://user-images.githubusercontent.com/54276661/186468882-41547819-4e3b-447d-8ce2-5fa968bc9c4a.png)

**Comment by nexxeln** [comment]
> I did according to docs, and now when I do LSPInfo in cpp file, I get following error. How to remove sourcekit?
> 
> ![image](https://user-images.githubusercontent.com/54276661/186468495-643ee50b-de35-4b64-a2dc-981c9976d8c3.png)

Looks like you haven't installed the language server

**Comment by nexxeln** [comment]
Not really sure tbh, google around a bit I guess, I have no idea how to cpp ecosystem works

**Comment by lakshits11** [comment]
![image](https://user-images.githubusercontent.com/54276661/186473141-fd381c16-864d-4e8e-b13e-aa65d1c7d0ba.png)

**Comment by lakshits11** [comment]
> Not really sure tbh, google around a bit I guess, I have no idea how to cpp ecosystem works


Its basic, previously, I just had language server installed and it worked out of the box, I used coc.nvim for auto completions before.

**Comment by nexxeln** [comment]
I'll leave this open if anyone knows how to do it, if you find a solution please share it here as well!

**Comment by VladoPlavsic** [comment]
This worked for me.
I tried removing `vim.cmd("colorscheme tokyodark")` from init.lua and it gave me other error, so I found this. 
Try to reinstall packer.
https://stackoverflow.com/questions/70462616/why-is-neovim-unable-to-locate-the-packer-module

**Comment by nexxeln** [comment]
Closing this because my config has changed now.
